#!/bin/bash
CRUN_VERSION="RC 1.1"

HELP="
This program compiles and run C code from command line, ex: crun 'print(\"%d\",getuid());'
it can be used as the #! shebang in a file, can read from stdin and also via an editor

	Usage: crun [options] [CC flags] [ < - | stdin | /dev/stdin> | <path/to/file>  | 'C function ...' ]
	--help                  print this help message
	--debug                 --verbose and --clean_all
	--verbose               turns bash -x on
	--clean_cache           clears the binary cache
	--clean_all             clears the binary cache and the source files
	--install               install crun @ /usr/bin/crun and exit

	* if you wish to include more header files files use -include <path/to/header> as CC flag, 
	** ALL posix header are already included by default, no need to include more
	*** This program uses the CC environment variable to compile otherwise fallback to gcc, then clang, then error

	example usage:

		$> crun 'printf(\"hello world\");'

		$> echo 'printf(\"hello world\");' | crun --clean_cache -Wall    # would clean the cache , compile with Wall the echoed function 

		we can also use a file!

		'''/some/path/to/a/file
		#!/usr/bin/crun
		printf(\"hello world\");
		'''
		$> crun --clean_cache -Wall /some/path/to/a/file

		$> crun                                                         # this opens an editor

		$> crun <<EOF                                                   # using heredoc
		printf(\"hello world\");
		EOF
"

#defaults
CRUN_DIR=~/.crun

CACHE_DIR=${CRUN_DIR}/cache

VERSION_FILE="${CRUN_DIR}/version"
HEADER_FILE="${CRUN_DIR}/main.h"
MAIN_FILE="${CRUN_DIR}/main.c"
MAIN_OBJ_FILE="${CRUN_DIR}/main.o"

CLEAN_CACHE="false"
CLEAN_ALL="false"
VERBOSE="false"
CRUN_EDITOR="vi"

input=""
	
# check that the current CC is usable otherwise unset
if [ "_${CC}" != "_" ];
then
	command -v "${CC}" &> /dev/null
else
	unset CC
fi

[ "_${CC}" == "_" ] && command -v clang &> /dev/null && CC="clang"
[ "_${CC}" == "_" ] && command -v gcc &> /dev/null && CC="gcc"


# check that the current CC is usable otherwise exit and error
if [ "_${CC}" == "_" ];
then
	echo "Unable to find a C compiler (CC=${CC} is not valid and gcc and clang don't exist )"
	exit 1
fi

# silence some clang warning
COMPILE="${CC} -std=iso9899:1999 -Wno-unused-command-line-argument"

PARSE_ARG="true"
while true; do
	if [ "${PARSE_ARG}" == "true" ];
	then
		case $1 in
			--help)
				echo "${HELP}"
				exit 0
				;;
			--debug)
				VERBOSE="true"
				CLEAN_ALL="true"
				shift
				;;
			--verbose)
				VERBOSE="true"
				shift
				;;
			--clean_cache)
				CLEAN_CACHE="true"
				shift
				;;
			--clean_all)
				CLEAN_ALL="true"
				shift
				;;
			--install)
				echo "installing crun @ /usr/usr/bin/crun"
				sudo /bin/bash -c "rm /usr/usr/bin/crun &> /dev/null; cp $0 /usr/usr/bin/crun"
				shift
				if [ "_$1" != "_" ]
				then
					/usr/usr/bin/crun "$@"
				fi
				exit $?
				;;
			*)
				PARSE_ARG="false"
				;;
		esac
	else
		if [ "_$1" == "_" ];
		then
			break;
		else
			COMPILE="${COMPILE} ${input}"
			input="$1"
			shift
		fi
	fi



done

if [ "_${VERBOSE}" == "_true" ];
then
	set -x
fi

function _set_editor() {
	CRUN_EDITOR=$(git var GIT_EDITOR)
	[ "_${CRUN_EDITOR}" == "_" ] && CRUN_EDITOR="${VISUAL}"
	[ "_${CRUN_EDITOR}" == "_" ] && CRUN_EDITOR="${EDITOR}"
	[ "_${CRUN_EDITOR}" == "_" ] && command -v vim &> /dev/null && CRUN_EDITOR="vim"
	[ "_${CRUN_EDITOR}" == "_" ] && command -v nano &> /dev/null && CRUN_EDITOR="nano"
	[ "_${CRUN_EDITOR}" == "_" ] && command -v vi &> /dev/null && CRUN_EDITOR="vi"
}

function _generate_header() {
echo "
/***************
* We use all the posix flags https://pubs.opengroup.org/onlinepubs/9699919799/idx/head.html
*/
#include <aio.h>
#include <libgen.h>
#include <spawn.h>
#include <sys/time.h>
#include <arpa/inet.h>
#include <limits.h>
#include <stdarg.h>
#include <sys/times.h>
#include <assert.h>
#include <locale.h>
#include <stdbool.h>
#include <sys/types.h>
#include <complex.h>
#include <math.h>
#include <stddef.h>
#include <sys/uio.h>
#include <cpio.h>
#include <monetary.h>
#include <stdint.h>
#include <sys/un.h>
#include <ctype.h>
// #include <mqueue.h>
#include <stdio.h>
#include <sys/utsname.h>
#include <dirent.h>
#include <ndbm.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <dlfcn.h>
#include <net/if.h>
#include <string.h>
#include <syslog.h>
#include <errno.h>
#include <netdb.h>
#include <strings.h>
#include <tar.h>
#include <fcntl.h>
#include <netinet/in.h>
// #include <stropts.h>
#include <termios.h>
#include <fenv.h>
#include <netinet/tcp.h>
#include <sys/ipc.h>
#include <tgmath.h>
#include <float.h>
#include <nl_types.h>
#include <sys/mman.h>
#include <time.h>
#include <fmtmsg.h>
#include <poll.h>
#include <sys/msg.h>
// #include <trace.h>
#include <fnmatch.h>
#include <pthread.h>
#include <sys/resource.h>
#include <ulimit.h>
#include <ftw.h>
#include <pwd.h>
#include <sys/select.h>
#include <unistd.h>
#include <glob.h>
#include <regex.h>
#include <sys/sem.h>
#include <utime.h>
#include <grp.h>
#include <sched.h>
#include <sys/shm.h>
#include <utmpx.h>
#include <iconv.h>
#include <search.h>
#include <sys/socket.h>
#include <wchar.h>
#include <inttypes.h>
#include <semaphore.h>
#include <sys/stat.h>
#include <wctype.h>
#include <iso646.h>
#include <setjmp.h>
#include <sys/statvfs.h>
#include <wordexp.h>
#include <langinfo.h>
#include <signal.h>

extern int errno;
int crun(void);

" > ${HEADER_FILE}

}

function _generate_main() {

echo "
#include \"${HEADER_FILE}\"

int main(void)
{
	errno = 0;
	return crun();
}
" > ${MAIN_FILE}

}

function _compile_main_o() {
	${COMPILE} -o "${MAIN_OBJ_FILE}" -c "${MAIN_FILE}" 
}

function _update_version() {
	echo "${CRUN_VERSION}" > ${VERSION_FILE}
}

function _clean_cache() {
	[ -d ${CACHE_DIR} ] && rm -Rf ${CACHE_DIR}
	mkdir -p ${CACHE_DIR}
	echo "clearing cache"
	CLEAN_CACHE="false"
}

function _clean_all() {
	[ -d ${CRUN_DIR} ] && rm -Rf ${CRUN_DIR}
	mkdir -p ${CRUN_DIR} && mkdir -p ${CACHE_DIR}
	echo "regenerating source files and clearing cache"
	CLEAN_ALL="false"
}

function _source_has_changed() {
	if	[ ! -d ${CRUN_DIR} ] ||
		[ ! -d ${CACHE_DIR} ] ||
		[ ! -f "${VERSION_FILE}" ]
		[ ! -f "${MAIN_OBJ_FILE}" ] ||
		[ ! -f "${MAIN_FILE}" ] ||
		[ ! -f "${HEADER_FILE}" ] ||
		[ "_${CRUN_VERSION}" != "_$(cat ${VERSION_FILE})" ];
	then
		CLEAN_ALL="true"
	fi
}

function _generate_C_from_file() {

	LINE_SKIP="1"
	if [ "_$(head --lines=1 ${input} | grep '#!')" != "_" ];
	then	
		LINE_SKIP=$(( ${LINE_SKIP} + 1 ))
	fi

	echo "int crun(void){{
	$(tail --lines=+${LINE_SKIP} ${input})
	;} return errno;}" > "$1"
}

function _generate_C_from_args() {
	echo "int crun(void){
		{${input};} 
		return errno;}" > "$1"
}

function _generate_C_from_stdin() {

	if [ ! -t 0 ];
	then
		echo "int crun(void){{" > "$1"

		while read -r input_text; do
			echo "${input_text}" >> "$1"
		done
		echo ";} return errno;}" >> "$1"
	else
		printf "/* this is the crun program main function, if you wich to know other usage, please rerun with --help */ \n\n int crun(void)\n{\n\t\n\t\n\treturn errno;\n}\n" > "$1"
		_set_editor
		${CRUN_EDITOR} "$1"
	fi
}

_source_has_changed

if  [ "${CLEAN_ALL}" == "true" ]
then
	_clean_all &&
	_generate_header &&
	_generate_main &&
	_compile_main_o &&
	_update_version
fi

if  [ "${CLEAN_CACHE}" == "true" ]
then
	_clean_cache
fi

#default
INPUT_NAME="arg"
case _${input} in
	_|_-|_/dev/stdin|_stdin)	INPUT_NAME="stdin"
		;;
	*)	[ -f "${input}" ] && 	INPUT_NAME="$(basename ${input})"
	;;
esac

TEMP_INPUT="${CACHE_DIR}/${INPUT_NAME}"
touch "${TEMP_INPUT}"

case "${INPUT_NAME}" in
	arg) 	_generate_C_from_args "${TEMP_INPUT}" ;;
	stdin)	_generate_C_from_stdin "${TEMP_INPUT}" ;;
	*)		_generate_C_from_file "${TEMP_INPUT}" ;;
esac

cd "${CACHE_DIR}" || ( echo "Unexepected error, ${CACHE_DIR} could not be created" && exit 1 )
HASHED_C_FILE="$(cksum "${INPUT_NAME}" | cut -d ' ' -f 1)"

if [ ! -f "${HASHED_C_FILE}" ];
then
	[ -f "${INPUT_NAME}" ] && ${COMPILE} -o "${HASHED_C_FILE}.o" -include "${HEADER_FILE}" -c "${INPUT_NAME}"
	[ -f "${HASHED_C_FILE}.o" ] && ${COMPILE} -o "${HASHED_C_FILE}" ${MAIN_OBJ_FILE} "${HASHED_C_FILE}.o"
fi

[ -f "${HASHED_C_FILE}.o" ] && rm "${HASHED_C_FILE}.o"
[ -f "${INPUT_NAME}" ] && rm "${INPUT_NAME}"

if [ -f "${HASHED_C_FILE}" ];
then
	"./${HASHED_C_FILE}"
	exit $?
else
	exit 1
fi
